import 'package:hive_flutter/hive_flutter.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'scanner_form_details.g.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
//part 'barcode_scanned_details.g.dart';

@HiveType(typeId: 1)
class ScannerFormDetails {
  ScannerFormDetails({
    required this.appointmentTime,
    required this.firstDateDateRange,
    required this.lastDateDateRange,
    required this.numberOfThings,
    required this.firstPriceRange,
    required this.lastPriceRange,
    required this.materialType,
  });

  @HiveField(2)
  DateTime appointmentTime;

  @HiveField(3)
  DateTime firstDateDateRange;

  @HiveField(4)
  DateTime lastDateDateRange;

  @HiveField(5)
  double numberOfThings;

  @HiveField(6)
  double firstPriceRange;

  @HiveField(7)
  double lastPriceRange;

  @HiveField(8)
  String materialType;
}
